{% set name = "dkist" %}
{% set version = "1.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dkist-{{ version }}.tar.gz
  sha256: 5dac6172dfded02e31208f3e553c8dc61e1478793036f2e882eb45435daab61e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=30.3.0
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp >=3.6
    - asdf >=2.11.0
    - asdf-astropy >=0.2.0
    - asdf-coordinates-schemas >=0.1.0
    - asdf-standard >=1.0.3
    - asdf-transform-schemas >=0.3.0
    - asdf-unit-schemas >=0.1.0
    - asdf-wcs-schemas >=0.3.0
    - astropy-base >=5.3
    - dask-core >=2021.8.0
    - globus-sdk >=3.0
    - gwcs >=0.19.0
    - matplotlib-base >=3.5
    - ndcube >=2.0
    - numpy >=1.22
    - parfive >=1.5
    - platformdirs >=3.0
    - sunpy >=4.0.7
    - tqdm  >=4.63

test:
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-doctestplus
    - pytest-remotedata
    - pytest-mock
    - pytest-mpl
    - pytest-httpserver
    - pytest-benchmark
    - pytest-lazy-fixtures
    - hypothesis
  imports:
    - dkist
  commands:
    - pip check
    - pytest --pyargs dkist -k "not test_fail" --remote-data=none -m "not mpl_image_compare"

about:
  home: http://dkist.nso.edu
  summary: DKIST User Tools
  license: BSD-3-Clause
  license_file: LICENSE.rst
  dev_url: https://github.com/DKISTDC/dkist

extra:
  recipe-maintainers:
    - Cadair
    - SolarDrew
